sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ******
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFqKQwrrRJKi6fQsS57
    access-key-secret: ******
    bucket-name: ywh-sky
  redis:
    host: localhost
    port: 6379
    datebase: 10
  wechat:
    appid: wx314025ef7f177e67
    secret: ******
